version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    container_name: mongo-server
    ports:
      - 27017:27017
    volumes:
      - ./apps/mongo:/data/db
